### ISSUE TITLE
Improve Slide Navigation Buttons

### ISSUE THREAD

**Issue by danprince** [eeue56/SlideShower#1]
At the moment the slide navigation buttons are clunky and don't fade in properly.
# MAKE IT PRETTY

**Comment by subsidel** [comment]
Suggestion: Change fade in to slow?

**Comment by danprince** [comment]
They aren't doing a fade of any kind (at any speed) in Chrome 26.0.1410.43 m.

**Comment by subsidel** [comment]
Strange, working beautifully in Chromium Version 25.0.1364.160

**Comment by subsidel** [comment]
And working in Chrome Version 26.0.1410.43 on Ubuntu 12.04

**Comment by danprince** [comment]
Ah, we're talking about different things, I'm on about the navigation buttons, rather than the images themselves.

**Comment by subsidel** [comment]
So this isn't about the buttons fading?

**Comment by eeue56** [comment]
Redundant, please use remark or something instead
