### ISSUE TITLE
Add Slide Numbers

### ISSUE THREAD

**Issue by danprince** [eeue56/SlideShower#2]
Add an overlay with the number of the current slide and the number of slides in the show.

E.g. 16/31

**Comment by eeue56** [comment]
Redundant, please use remark or something instead

**Comment by danprince** [comment]
@eeue56 I've been waiting for this to be fixed for nearly 4 years, don't think you can just get away with suggesting a crummy little library like remark as an alternative.

**Comment by gabrielguimaraes** [comment]
Don't fight guys! =)

**Comment by eeue56** [comment]
It's okay, I've got a fix. There's this new free tool called Power Points. https://products.office.com/en/powerpoint Please use this instead.

**Comment by danprince** [comment]
84% of my startup's revenue streams are built around SlideShower. We sponsored the project for 20 months. We can't just "use this instead".

You've just lost a valuable contributor.

**Comment by danprince** [comment]
Plus, these Power Points doesn't support markdown and you can't install them from npm.

**Comment by eeue56** [comment]
I'll provide you with some slides you can use to continue your market growth.

![](https://github.com/eeue56/SlideShower/raw/master/slides/slide1.png)
![](https://github.com/eeue56/SlideShower/raw/master/slides/slide2.png)
![](https://github.com/eeue56/SlideShower/raw/master/slides/slide3.png)
![](https://github.com/eeue56/SlideShower/raw/master/slides/slide4.png)

As everyone knows, I poured both my hearts and my tears into this at 3am while singing traditional Welsh songs. It saddens me to suggest moving to superior products, but this project's all out of water
