### ISSUE TITLE
Missing CONTRIBUTING file

### ISSUE THREAD

**Issue by subsidel** [eeue56/SlideShower#3]
I believe that there should be a contributing guidelines file.
Contribution guidelines are a way to quickly communicate how people should contribute, and would greatly help new contributors.
It should include things like:
# What should I know before I get started?
* Code of Conduct
* SlideShower Design Decisions
* How to use RemarkJS
# How Can I Contribute?
* Reporting Bugs
* Suggesting Enhancements
* Your First Code Contribution
* Pull Requests
* Git Commit Messages
* JavaScript Styleguide
* PHP Anti-Styleguide
* Documentation Styleguide
# Additional Notes
* Which Traditional Welsh Songs Should Be Sung Whilst Developing
* List Of Forbidden Songs
* Issue and Pull Request Labels

**Comment by danprince** [comment]
Got things kicked off in #4.
